export enum EAvailableCountries {
  AUSTRALIA = 'au',
  BRAZIL = 'br',
  CANADA = 'ca',
  CHINA = 'cn',
  EGYPT = 'eg',
  FRANCE = 'fr',
  GERMANY = 'de',
  GREECE = 'gr',
  HONG_KONG = 'hk',
  INDIA = 'in',
  IRELAND = 'ie',
  ISRAEL = 'il',
  ITALY = 'it',
  JAPAN = 'jp',
  NETHERLANDS = 'nl',
  NORWAY = 'no',
  PAKISTAN = 'pk',
  PERU = 'pe',
  PHILIPPINES = 'ph',
  PORTUGAL = 'pt',
  ROMANIA = 'ro',
  RUSSIAN_FEDERATION = 'ru',
  SINGAPORE = 'sg',
  SPAIN = 'es',
  SWEDEN = 'se',
  SWITZERLAND = 'ch',
  TAIWAN = 'tw',
  UKRAINE = 'ua',
  UNITED_KINGDOM = 'gb',
  UNITED_STATES = 'us',
}

export enum EAvailableLanguages {
  ARABIC = 'ar',
  CHINESE = 'zh',
  DUTCH = 'nl',
  ENGLISH = 'en',
  FRENCH = 'fr',
  GERMAN = 'de',
  GREEK = 'el',
  HEBREW = 'he',
  HINDI = 'hi',
  ITALIAN = 'it',
  JAPANESE = 'ja',
  MALAYALAM = 'ml',
  MARATHI = 'mr',
  NORWEGIAN = 'no',
  PORTUGUESE = 'pt',
  ROMANIAN = 'ro',
  RUSSIAN = 'ru',
  SPANISH = 'es',
  SWEDISH = 'sv',
  TAMIL = 'ta',
  TELUGU = 'te',
  UKRAINIAN = 'uk',
}

export enum HTTPMethods {
  GET = 'GET',
  POST = 'POST',
  DELETE = 'DELETE',
  UPDATE = 'UPDATE',
}
